$( function() {
    var topCities = [
        'New York, NY',
        'Los Angeles, CA',
        'Chicago, IL',
        'Houston, TX',
        'Phoenix, AZ',
        'Philadelphia, PA',
        'San Antonio, TX',
        'San Diego, CA',
        'Dallas, TX',
        'San Jose, CA',
        'Austin, TX',
        'Jacksonville, FL',
        'Fort Worth, TX',
        'Columbus, OH',
        'Charlotte, NC',
        'San Francisco, CA',
        'Indianapolis, IN',
        'Seattle, WA',
        'Denver, CO',
        'Washington, D.C.',
        'Boston, MA',
        'El Paso, TX',
        'Detroit, MI',
        'Nashville, TN',
        'Memphis, TN',
        'Portland, OR',
        'Oklahoma City, OK',
        'Las Vegas, NV',
        'Louisville, KY',
        'Baltimore, MD',
        'Milwaukee, WI',
        'Albuquerque, NM',
        'Tucson, AZ',
        'Fresno, CA',
        'Mesa, AZ',
        'Sacramento, CA',
        'Atlanta, GA',
        'Kansas City, MO',
        'Colorado Springs, CO',
        'Miami, FL',
        'Raleigh, NC',
        'Omaha, NE',
        'Long Beach, CA',
        'Virginia Beach, VA',
        'Oakland, CA',
        'Minneapolis, MN',
        'Tulsa, OK',
        'Arlington, TX',
        'Tampa, FL',
        'New Orleans, LA',
        'Wichita, KS',
        'Bakersfield, CA',
        'Cleveland, OH',
        'Aurora, CO',
        'Anaheim, CA',
        'Honolulu, HI',
        'Santa Ana, CA',
        'Riverside, CA',
        'Corpus Christi, TX',
        'Lexington, KY',
        'Stockton, CA',
        'Henderson, NV',
        'Saint Paul, MN',
        'St. Louis, MO',
        'Cincinnati, OH',
        'Pittsburgh, PA',
        'Greensboro, NC',
        'Anchorage, AK',
        'Plano, TX',
        'Lincoln, NE',
        'Orlando, FL',
        'Irvine, CA',
        'Newark, NJ',
        'Durham, NC',
        'Chula Vista, CA',
        'Toledo, OH',
        'Fort Wayne, IN',
        'St. Petersburg, FL',
        'Laredo, TX',
        'Jersey City, NJ',
        'Chandler, AZ',
        'Madison, WI',
        'Lubbock, TX',
        'Scottsdale, AZ',
        'Reno, NV',
        'Buffalo, NY',
        'Gilbert, AZ',
        'Glendale, AZ',
        'North Las Vegas, NV',
        'Winston-Salem, NC',
      ];
      
    $( "#auto-complete" ).autocomplete({
      source: topCities
    });
  } );